### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Luongzz** [Practicer45000/Tiktok-Viewbot-Sharebot#3]
`loading...
Traceback (most recent call last):
  File "C:\Users\Yoshino\Desktop\Bot\toptop\Tiktok-Viewbot-Sharebot-main\main.py", line 158, in <module>
    config = json.load(f)
             ^^^^^^^^^^^^
  File "C:\Users\Yoshino\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Yoshino\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoshino\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoshino\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Nain00o5** [comment]
Same as mine if you get ans then share details
